# Generated by Django 5.2.10 on 2026-01-22 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="post",
            options={"ordering": ["-update_at"]},
        ),
        migrations.AddField(
            model_name="post",
            name="region",
            field=models.CharField(
                choices=[
                    ("Europe", "유럽"),
                    ("Asia", "아시아"),
                    ("Oceania", "오세아니아"),
                    ("Ameria", "아메리카"),
                    ("Africa", "아프리카"),
                ],
                default="Asia",
                max_length=100,
                verbose_name="지역",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="post",
            unique_together={("title", "content")},
        ),
    ]
