# Generated by Django 5.2.10 on 2026-01-22 01:51

import blog.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0002_alter_post_options_post_region_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="lnglat",
            field=models.CharField(
                blank=True,
                help_text="경도,위도 포맷 ex.37,125.5",
                max_length=100,
                null=True,
                validators=[blog.models.lnglat_validator],
                verbose_name="경,위도",
            ),
        ),
        migrations.AddField(
            model_name="post",
            name="url",
            field=models.URLField(blank=True, null=True),
        ),
    ]
