# Generated by Django 5.2.10 on 2026-01-22 02:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0003_post_lnglat_post_url"),
    ]

    operations = [
        migrations.CreateModel(
            name="Comment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "author",
                    models.CharField(
                        blank=True, max_length=20, null=True, verbose_name="댓글쓴이"
                    ),
                ),
                ("message", models.TextField(verbose_name="댓글")),
                ("create_at", models.DateField(auto_now_add=True)),
                ("update_at", models.DateTimeField(auto_now=True)),
                (
                    "post",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="blog.post"
                    ),
                ),
            ],
            options={
                "ordering": ["-update_at"],
                "unique_together": {("post", "author", "message")},
            },
        ),
    ]
