-- [V] Sequence : 순차번호 생성기. 대부분 인위적인 PK 사용 용도
DROP SEQUENCE FRIEND_SQ;
CREATE SEQUENCE FRIEND_SQ 
  START WITH 10 -- 1부터 생성(기본값:1)
  INCREMENT BY -1 -- 1씩 증가(기본값)
  MAXVALUE 9999 -- 최대값
  MINVALUE -9999 -- 최소값
  NOCYCLE       
  NOCACHE;      -- 캐시메모리를 사용 안 함
SELECT FRIEND_SQ.NEXTVAL FROM DUAL; -- NEXTVAL(순차번호생성), DUAL:오라클 제공 테이블(1행1열)
SELECT FRIEND_SQ.CURRVAL FROM DUAL; -- CURRVAL(현재까지 진행된 순차번호)

-- ex. 시퀀스를 이용한 FRIEND테이블 
DROP TABLE FRIEND;
CREATE TABLE FRIEND(
  NO   NUMBER(5) PRIMARY KEY,
  NAME VARCHAR2(30) NOT NULL,
  TEL  VARCHAR2(20) UNIQUE,
  ADDRESS VARCHAR2(255),
  LAST_MODIFY DATE DEFAULT SYSDATE
);
DROP SEQUENCE FRIEND_SQ;
CREATE SEQUENCE FRIEND_SQ MAXVALUE 99999 NOCACHE NOCYCLE;

INSERT INTO FRIEND (NO, NAME, TEL, ADDRESS) 
  VALUES (FRIEND_SQ.NEXTVAL, '홍길동', NULL, '신림'); -- 여러번 실행 가능
SELECT NO, NAME, TEL, ADDRESS, 
    TO_CHAR(LAST_MODIFY, 'RR/MM/DD AM HH:MI:SS') LAST_MODIFY
  FROM FRIEND;
INSERT INTO FRIEND
  VALUES (FRIEND_SQ.NEXTVAL, '김길동', '010-9988-9999', '봉천', SYSDATE);
  
-- ※※※ 연습문제 ※※※
-- 테이블 및 시퀀스 삭제
DROP TABLE MEMBER;
DROP TABLE MEMBER_LEVEL CASCADE CONSTRAINTS;
DROP SEQUENCE MEMBER_MNO_SQ;
-- 테이블 및 시퀀스 생성
CREATE TABLE MEMBER_LEVEL(
  LEVELNO NUMBER(1) PRIMARY KEY,
  LEVELNAME VARCHAR2(20) NOT NULL
);
CREATE TABLE MEMBER(
    mNO     NUMBER(4)    PRIMARY KEY,
    mNAME   VARCHAR2(20) NOT NULL,
    mPW     VARCHAR2(8)  NOT NULL,
    -- mPW     VARCHAR2(8)  CHECK(LENGTH(MPW) BETWEEN 1 AND 8),
    mEMAIL  VARCHAR2(30) UNIQUE,
    mPOINT  NUMBER(10)   DEFAULT 1000 CHECK(mPOINT>=0),
    mRDATE  DATE         DEFAULT SYSDATE,
    LEVELNO NUMBER(1)    REFERENCES MEMBER_LEVEL(LEVELNO) 
);
CREATE SEQUENCE MEMBER_MNO_SQ MAXVALUE 9999 NOCACHE NOCYCLE;
-- 데이터 입력
INSERT INTO MEMBER_LEVEL VALUES (-1, 'black');
INSERT INTO MEMBER_LEVEL VALUES (0, '일반');
INSERT INTO MEMBER_LEVEL VALUES (1, '실버');
INSERT INTO MEMBER_LEVEL VALUES (2, '골드');
SELECT * FROM MEMBER_LEVEL;
INSERT INTO MEMBER (mNO, mNAME, mPW, mEMAIL, mPOINT, LEVELNO)
    VALUES (MEMBER_MNO_SQ.NEXTVAL, '홍길동', 'aa', 'hong@hong.com', 0, 0);
INSERT INTO MEMBER (mNO, mNAME, mPW, mEMAIL, mRDATE, LEVELNO)
    VALUES (MEMBER_MNO_SQ.NEXTVAL, '신길동', 'bb', 'sin@sin.com', 
            TO_DATE('22/04/01','RR/MM/DD'), 1);
SELECT * FROM MEMBER;

-- 데이터 출력
SELECT MNO, MNAME, TO_CHAR(MRDATE, 'YYYY-MM-DD') mEMAIL, MPOINT POINT, 
    LEVELNAME||'고객' LEVELNAME
  FROM MEMBER M, MEMBER_LEVEL L
  WHERE M.LEVELNO = L.LEVELNO;
  
SELECT MNO, MNAME, TO_CHAR(MRDATE, 'YYYY-MM-DD') mEMAIL, MPOINT POINT,
    CASE LEVELNO
      WHEN -1 THEN 'black회원'
      WHEN 0 THEN '일반회원'
      WHEN 1 THEN '실버회원'
      WHEN 2 THEN '골드회원'
    END LEVELNAME
  FROM MEMBER;
  
  
  