-- [V] Sequence : 순차번호 생성기. 대부분 인위적인 PK 사용 용도
DROP SEQUENCE FRIEND_SQ;
CREATE SEQUENCE FRIEND_SQ 
  START WITH 10 -- 1부터 생성(기본값:1)
  INCREMENT BY -1 -- 1씩 증가(기본값)
  MAXVALUE 9999 -- 최대값
  MINVALUE -9999 -- 최소값
  NOCYCLE       
  NOCACHE;      -- 캐시메모리를 사용 안 함
SELECT FRIEND_SQ.NEXTVAL FROM DUAL; -- NEXTVAL(순차번호생성), DUAL:오라클 제공 테이블(1행1열)
SELECT FRIEND_SQ.CURRVAL FROM DUAL; -- CURRVAL(현재까지 진행된 순차번호)

-- ex. 시퀀스를 이용한 FRIEND테이블 
DROP TABLE FRIEND;
CREATE TABLE FRIEND(
  NO   NUMBER(5) PRIMARY KEY,
  NAME VARCHAR2(30) NOT NULL,
  TEL  VARCHAR2(20) UNIQUE,
  ADDRESS VARCHAR2(255),
  LAST_MODIFY DATE DEFAULT SYSDATE
);
DROP SEQUENCE FRIEND_SQ;
CREATE SEQUENCE FRIEND_SQ MAXVALUE 99999 NOCACHE NOCYCLE;

INSERT INTO FRIEND (NO, NAME, TEL, ADDRESS) 
  VALUES (FRIEND_SQ.NEXTVAL, '홍길동', NULL, '신림'); -- 여러번 실행 가능
SELECT NO, NAME, TEL, ADDRESS, 
    TO_CHAR(LAST_MODIFY, 'RR/MM/DD AM HH:MI:SS') LAST_MODIFY
  FROM FRIEND;







