"""
Django settings for myproject project.

Generated by 'django-admin startproject' using Django 5.2.10.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
1. SECRET_KEY 처리(.env)
2. 앱등록
3. myproject밑에 templates폴더(base.html, header.html, footer.hmtl)와 static폴더 추가 후 등록
4. 한국어 등록 (admin 페이지)
5. 한국 timezone 등록
"""

from pathlib import Path
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent
# print('프로젝트 루트 폴더 :', BASE_DIR)
# print(os.path.join(BASE_DIR, 'myproject', 'templates'))

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
from dotenv import load_dotenv

load_dotenv()
SECRET_KEY = os.getenv("SECRET_KEY", "scretkey")

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

# ALLOWED_HOSTS = ['192.168.0.52', '127.0.0.1']
# "192.168.0.52,127.0.0.1" => ['192.168.0.52', '127.0.0.1']
# python manage.py runserver 192.168.0.52:80로 서버 실행
ALLOWED_HOSTS = os.getenv('ALLOWED_HOSTS', default="127.0.0.1").split(',')
# print(ALLOWED_HOSTS)

# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "blog", # 앱등록
    "accounts",
    "book",
    "django.contrib.humanize", # intcomma(세자리마다 ,) 필터 사용
    "article", # v1. GenericView이용(paging처리), v2.검색기능 v3.파일첨부(ch08)
    "filetest",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "myproject.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [
            os.path.join(BASE_DIR, 'myproject', 'templates'),
        ],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "myproject.wsgi.application"


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.sqlite3",
        "NAME": BASE_DIR / "db.sqlite3",
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    # {
    #     "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    # }, # 다른 개인정보와 유사한 비밀번호 사용 불가
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
        "OPTIONS": {"min_length":2}
    }, # 최소 2자 이상 비밀번호
    # {
    #     "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    # }, # 통상적으로 자주사용되는 비밀번호 사용 불가
    # {
    #     "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    # }, # 숫자만 이루어진 비밀번호 사용 불가
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

# LANGUAGE_CODE = "en-us"
LANGUAGE_CODE = "ko-kr" # 장고 admin 페이지 언어
# TIME_ZONE = "UTC"
TIME_ZONE = "Asia/Seoul"
USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/
'''
Django 프로젝트가 실행 -> 설정이 셋팅(settings.py)
1. django.conf.global_settings.py 로드(모든 기본값)
2. 사용자의 settings.py로드(프로젝트별 존재)
'''
# 개발 환경
STATIC_URL = "/static/" # 앱폴더 밑의 static
STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'myproject', 'static')
]
# 배포 후 운영환경(2월) : 모든 static을 STATIC_ROOT로 옮기기 - python manage.py collectstatic
STATIC_ROOT = os.path.join(BASE_DIR, '_staticfiles')

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

# 업로드한 파일이 저장될 폴더와 액세스 url
# /media/folder/a.png url로 접근 => _media/folder/a.png저장
MEDIA_URL = "/media/"
MEDIA_ROOT = os.path.join(BASE_DIR, "_media")
# myproject/urls.py에 MEDIA_URL와 ROOT연결