DROP TABLE TODO;
DROP SEQUENCE TODO_SQ;
CREATE TABLE TODO(
  ID NUMBER(4) PRIMARY KEY, -- 번호
  CONTENT VARCHAR2(256) NOT NULL, -- 할일
  IS_DONE  NUMBER(1) DEFAULT 0 -- 수행여부
);
CREATE SEQUENCE TODO_SQ NOCACHE NOCYCLE MAXVALUE 9999;

-- CREATE
INSERT INTO TODO (ID, CONTENT) VALUES (TODO_SQ.NEXTVAL, 'flask');
INSERT INTO TODO (ID, CONTENT) VALUES (TODO_SQ.NEXTVAL, '프로젝트발표');
INSERT INTO TODO (ID, CONTENT) VALUES (TODO_SQ.NEXTVAL, '포트폴리오작성');

-- next_id
SELECT NVL(MAX(ID), 0)+1 FROM TODO;

-- READ
SELECT * FROM TODO ORDER BY ID desc;
SELECT * FROM TODO WHERE ID = 1;

-- UPDATE
UPDATE TODO SET CONTENT='바꿀내용', IS_DONE=1 WHERE ID=1;

-- DELETE
DELETE FROM TODO WHERE ID=2;
COMMIT;





