# Generated by Django 5.2.10 on 2026-01-19 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Student",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=100, unique=True)),
                ("major", models.CharField(blank=True, max_length=100, null=True)),
                ("age", models.IntegerField(default=20)),
                ("grade", models.IntegerField(default=1)),
            ],
        ),
    ]
