# Generated by Django 5.2.10 on 2026-01-29 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("article", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="article",
            options={"ordering": ["-id"]},
        ),
        migrations.AddField(
            model_name="article",
            name="photo",
            field=models.ImageField(blank=True, upload_to="", verbose_name="사진"),
        ),
    ]
