# Generated by Django 5.2.10 on 2026-02-03 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("article", "0002_alter_article_options_article_photo"),
    ]

    operations = [
        migrations.AlterField(
            model_name="article",
            name="photo",
            field=models.ImageField(
                blank=True, upload_to="article/%Y/%m/%d", verbose_name="사진"
            ),
        ),
    ]
